name: Run Symfony Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: symfony
          POSTGRES_DB: criti-pixel
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U symfony"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: "postgresql://symfony:symfony@localhost:5432/criti-pixel"
      APP_ENV: test
      SYMFONY_DEPRECATIONS_HELPER: disabled

    steps:
      - uses: actions/checkout@v4

      - name: Install Symfony CLI
        run: curl -sS https://get.symfony.com/cli/installer | bash && mv ~/.symfony*/bin/symfony /usr/local/bin/symfony

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_pgsql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      - name: Build Sass css
        run: symfony console sass:build
        
      - name: Clear cache for test env
        run: php bin/console cache:clear --env=test

      - name: Run test suite
        run: composer run test
